# Generated by Django 2.0 on 2019-11-08 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='email',
            new_name='emailid',
        ),
        migrations.RenameField(
            model_name='emailid',
            old_name='eid',
            new_name='email',
        ),
    ]
