# Generated by Django 2.0 on 2019-11-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='i',
        ),
        migrations.AddField(
            model_name='post',
            name='i',
            field=models.ManyToManyField(related_name='images', to='blog.images'),
        ),
    ]
